spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gmall-product
          predicates:
            - Path=/api/category/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: product_route_brand
          uri: lb://gmall-product
          predicates:
            - Path=/api/brand/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://gamll-renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}